// Shared content for all 3 portfolio variations.
// Bilingual FR/EN. First-person voice.

window.PORTFOLIO_CONTENT = {
  fr: {
    nav: { work: 'Parcours', projects: 'Projets', skills: 'Compétences', contact: 'Contact' },
    hero: {
      kicker: 'Étudiant développeur · Valence, France',
      name: 'Roman Rodriguez',
      role: 'Développeur full-stack & mobile',
      tagline: 'Je suis en 3ᵉ année de BUT Informatique en alternance chez KDS, où je conçois des outils internes — applications mobiles, sites web et CRM — au service d\u2019une logique métier exigeante.',
      cta1: 'Voir mes projets',
      cta2: 'Télécharger mon CV',
    },
    about: {
      title: 'À propos',
      paragraphs: [
        'Je suis en 3ᵉ année de BUT Informatique, parcours « Réalisation d\u2019applications », à l\u2019IUT de Valence (Université Grenoble Alpes).',
        'J\u2019aborde chaque projet de la même façon : j\u2019écoute, je cherche à comprendre le besoin réel, puis je livre une solution claire — qu\u2019il s\u2019agisse d\u2019un site vitrine médical, d\u2019une carte interactive métier ou d\u2019une application mobile pour des audits terrain.',
        'Curieux par défaut, je continue d\u2019élargir ma palette technique au-delà du cadre académique : Rust, infrastructure ESXi, CI/CD GitLab.',
      ],
      values: [
        { k: 'Écoute', v: 'Comprendre avant de coder' },
        { k: 'Rigueur', v: 'Modélisation, tests, documentation' },
        { k: 'Curiosité', v: 'Une nouvelle stack par trimestre' },
      ],
    },
    work: {
      title: 'Parcours',
      items: [
        {
          period: '2025 — 2026',
          role: 'Développeur Mobile & CRM · Alternance',
          org: 'KDS',
          logo: 'assets/logo-kds.webp',
          summary: 'Trois outils internes au service des audits de copropriétés : application mobile photo/dossier, carte interactive métier et CRM Airtable.',
          projects: ['audit-app', 'kds-map', 'crm-airtable'],
        },
        {
          period: '2024 — 2025',
          role: 'Développeur Full-Stack · Stage',
          org: 'Dr J. Chandezon',
          logo: 'assets/icon-chandezon.webp',
          summary: 'Site vitrine et espace patient d’un cabinet médical, de la maquette Figma à la mise en ligne sur drchandezon.fr.',
          projects: ['chandezon'],
        },
        {
          period: '2025 — 2026',
          role: 'SAÉ · Application mobile transpalette',
          org: 'Intermarché — Les Mousquetaires',
          logo: 'assets/logo-mousquetaires.webp',
          summary: 'Application mobile embarquée sur transpalette pour guider les préparateurs de commandes en entrepôt réfrigéré.',
          projects: ['mousquetaires'],
        },
      ],
    },
    projects: {
      title: 'Projets sélectionnés',
      items: [
        {
          id: 'audit-app',
          featured: true,
          name: 'PhotoKDS — Application d\u2019audits',
          context: 'KDS · 2025 — en cours',
          stack: ['Flutter', 'React Native', 'iOS', 'Android'],
          icon: 'assets/icon-audit-app.webp',
          gallery: [
            'assets/screenshot-photokds-home.webp',
            'assets/screenshot-photokds-camera.webp',
            'assets/screenshot-photokds-export.webp',
          ],
          summary: 'Application mobile interne PhotoKDS permettant aux équipes terrain de constituer dossiers photo et rapports d\u2019intervention pendant les audits de copropriétés.',
          contributions: [
            { t: 'Offline-first', d: 'Architecture pensée pour les chantiers sans réseau' },
            { t: 'Capture photo', d: 'Organisée par dossier et par copropriété' },
            { t: 'Export structuré', d: 'Vers Downloads ou archive ZIP' },
            { t: 'Thématisation', d: 'Personnalisation complète de l\u2019interface' },
          ],
        },
        {
          id: 'kds-map',
          video: 'assets/kds-map-demo.mp4',
          name: 'Carte interactive KDS',
          context: 'KDS · 2025',
          stack: ['JavaScript', 'API cartographiques'],
          icon: 'assets/icon-kds-map.webp',
          screenshot: 'assets/screenshot-kds-map.webp',
          summary: 'Carte interactive métier permettant la visualisation et la sélection des dossiers d\u2019audit géolocalisés sur l\u2019ensemble du parc.',
          contributions: [
            { t: 'UX de filtrage', d: 'Par étape, type et organisation' },
            { t: 'Vue satellite', d: 'Clusters de logements sur tout le parc' },
            { t: 'Données métier', d: 'Intégration en temps réel' },
          ],
        },
        {
          id: 'mousquetaires',
          video: 'assets/mousquetaires-demo.mp4',
          name: 'App mobile transpalette · Intermarché',
          context: 'SAÉ · IUT Valence × Les Mousquetaires · 2025-2026',
          stack: ['React', 'Symfony', 'API REST'],
          logo: 'assets/logo-mousquetaires.webp',
          screenshot: 'assets/screenshot-mousquetaires-dashboard.webp',
          gallery: [
            'assets/screenshot-mousquetaires-login.webp',
            'assets/screenshot-mousquetaires-dashboard.webp',
            'assets/screenshot-mousquetaires-dashboard-2.webp',
            'assets/screenshot-mousquetaires-gestion.webp',
            'assets/screenshot-mousquetaires-supports.webp',
            'assets/screenshot-mousquetaires-preparation.webp',
          ],
          summary: 'Application mobile embarquée sur transpalette destinée aux préparateurs de commandes en entrepôt réfrigéré, conçue pour les guider et fluidifier leurs tournées.',
          contributions: [
            { t: 'Besoins terrain', d: 'Recueil sur site, en entrepôt frigorifique' },
            { t: 'Front React', d: 'Adapté à l\u2019usage gants + écran tactile' },
            { t: 'API Symfony', d: 'Gestion des tournées de préparation' },
          ],
        },
        {
          id: 'crm-airtable',
          name: 'CRM interne Airtable',
          context: 'KDS · 2025',
          stack: ['Airtable', 'Automatisations', 'Intégrations'],
          logo: 'assets/airtable-logo.webp',
          summary: 'Mise en place d\u2019un CRM Airtable de bout en bout : modélisation, automatisations et intégration aux flux internes.',
          contributions: [
            { t: 'Audit', d: 'Analyse des processus existants' },
            { t: 'Modélisation', d: 'Relations entre les entités du CRM' },
            { t: 'Automatisations', d: 'Vues et flux filtrés par équipe' },
          ],
        },
        {
          id: 'chandezon',
          video: 'assets/chandezon-demo.mp4',
          name: 'Site Dr Chandezon',
          context: 'Stage · 2024 — 2025',
          stack: ['PHP', 'MySQL', 'HTML/CSS', 'Figma'],
          logo: 'assets/icon-chandezon.webp',
          screenshot: 'assets/screenshot-chandezon.webp',
          gallery: [
            'assets/screenshot-chandezon.webp',
            'assets/screenshot-chandezon-about.webp',
            'assets/screenshot-chandezon-care.webp',
          ],
          summary: 'Site vitrine et espace patient pour un cabinet de médecine morphologique et anti-âge. De la maquette Figma au déploiement.',
          contributions: [
            { t: 'Maquettes Figma', d: 'Prototypes interactifs validés avec le client' },
            { t: 'Full-Stack', d: 'Développement PHP/MySQL et base relationnelle' },
            { t: 'Mise en ligne', d: 'Déployé sur drchandezon.fr' },
          ],
          link: 'https://drchandezon.fr',
        },
      ],
    },
    skills: {
      title: 'Compétences techniques',
      groups: [
        { label: 'Développement Web', items: ['HTML/CSS', 'JavaScript', 'TypeScript', 'PHP', 'React', 'Symfony'] },
        { label: 'Développement Logiciel', items: ['Java', 'Python', 'C', 'C++', 'C#', 'Rust'] },
        { label: 'Mobile', items: ['Flutter', 'React Native', 'React Expo', 'Kotlin'] },
        { label: 'Bases de données', items: ['SQL', 'Neo4j', 'Firestore', 'Power BI'] },
        { label: 'Outils & Méthodes', items: ['Docker', 'GitLab CI/CD', 'ESXi', 'Godot', 'Modélio'] },
      ],
    },
    education: {
      title: 'Formation',
      items: [
        { period: '2023 — 2026', degree: 'BUT Informatique · Réalisation d\u2019applications', school: 'IUT de Valence — UGA · 3e année en alternance', logo: 'assets/logo-iut-valence.webp' },
        { period: '2022 — 2023', degree: 'Baccalauréat général · Mention Assez Bien', school: 'Lycée les Catalins, Montélimar' },
      ],
    },
    interests: {
      title: 'Centres d\u2019intérêt',
      music: {
        label: 'Musique',
        lead: 'Je passe une bonne partie de mon temps libre dans des casques. Trois familles surtout :',
        genres: [
          { name: 'Jazz Rap', note: 'Samples de cuivres, flow posé, lyrics travaillés' },
          { name: 'Soul', note: 'Voix, groove, classiques 60s–70s' },
          { name: 'R&B', note: 'Production moderne, atmosphères nocturnes' },
        ],
      },
      items: [
        { k: 'Football', v: 'Pratique occasionnelle, suivi des compétitions' },
        { k: 'Journalisme & géopolitique', v: 'Suivi de l\u2019actualité internationale' },
        { k: 'Culture audiovisuelle', v: 'Cinéma, séries, documentaires' },
      ],
    },
    contact: {
      title: 'Contact',
      lead: 'Je suis disponible pour échanger sur une opportunité, un projet ou une candidature école.',
      email: 'roman.theo.rodriguez@gmail.com',
      phone: '07 50 02 64 78',
      city: 'Valence, France',
      languages: 'Français · Anglais B2 · Espagnol A2',
      cv: 'Télécharger le CV (PDF)',
      linkedin: 'https://www.linkedin.com/in/roman-rodriguez-b34a96376/',
      github: 'https://github.com/Vaxen69',
    },
    misc: { available: 'Disponible · alternance & école d\u2019ingénieur', viewProject: 'Voir le projet', backToList: 'Retour' },
  },
  en: {
    nav: { work: 'Journey', projects: 'Projects', skills: 'Skills', contact: 'Contact' },
    hero: {
      kicker: 'CS student & developer · Valence, France',
      name: 'Roman Rodriguez',
      role: 'Full-stack & mobile developer',
      tagline: 'I\u2019m a third-year CS student in a work-study program at KDS, where I build internal tools — mobile apps, websites and CRMs — for demanding business processes.',
      cta1: 'See my projects',
      cta2: 'Download my résumé',
    },
    about: {
      title: 'About',
      paragraphs: [
        'I\u2019m a third-year CS student in the “Application Development” track at IUT de Valence (Université Grenoble Alpes).',
        'I approach every project the same way: I listen, I try to understand the actual need, then I ship a clear solution — whether it\u2019s a medical practice site, a domain-specific interactive map or a mobile app for field audits.',
        'Curious by default, I keep broadening my stack beyond the syllabus: Rust, ESXi infrastructure, GitLab CI/CD.',
      ],
      values: [
        { k: 'Listening', v: 'Understand before coding' },
        { k: 'Rigor', v: 'Modeling, testing, documentation' },
        { k: 'Curiosity', v: 'A new stack every term' },
      ],
    },
    work: {
      title: 'Journey',
      items: [
        {
          period: '2025 — 2026',
          role: 'Mobile & CRM Developer · Apprenticeship',
          org: 'KDS',
          logo: 'assets/logo-kds.webp',
          summary: 'Three internal tools supporting condominium audits: a photo/case-file mobile app, a domain-specific interactive map and an Airtable CRM.',
          projects: ['audit-app', 'kds-map', 'crm-airtable'],
        },
        {
          period: '2024 — 2025',
          role: 'Full-Stack Developer · Internship',
          org: 'Dr J. Chandezon',
          logo: 'assets/icon-chandezon.webp',
          summary: 'Showcase site and patient portal for a medical practice — from Figma mockups to going live at drchandezon.fr.',
          projects: ['chandezon'],
        },
        {
          period: '2025 — 2026',
          role: 'SAÉ · Pallet truck mobile app',
          org: 'Intermarché — Les Mousquetaires',
          logo: 'assets/logo-mousquetaires.webp',
          summary: 'Mobile app embedded on a pallet truck guiding order pickers through a refrigerated warehouse.',
          projects: ['mousquetaires'],
        },
      ],
    },
    projects: {
      title: 'Selected projects',
      items: [
        {
          id: 'audit-app',
          featured: true,
          name: 'PhotoKDS — audit app',
          context: 'KDS · 2025 — ongoing',
          stack: ['Flutter', 'React Native', 'iOS', 'Android'],
          icon: 'assets/icon-audit-app.webp',
          gallery: [
            'assets/screenshot-photokds-home.webp',
            'assets/screenshot-photokds-camera.webp',
            'assets/screenshot-photokds-export.webp',
          ],
          summary: 'Internal mobile app PhotoKDS letting field teams compile photo dossiers and reports during condominium audits.',
          contributions: [
            { t: 'Offline-first', d: 'Architecture designed for sites without coverage' },
            { t: 'Photo capture', d: 'Organized by case file and building' },
            { t: 'Structured export', d: 'To Downloads or a ZIP archive' },
            { t: 'Theming', d: 'Full UI customization' },
          ],
        },
        {
          id: 'kds-map',
          video: 'assets/kds-map-demo.mp4',
          name: 'KDS interactive map',
          context: 'KDS · 2025',
          stack: ['JavaScript', 'Mapping APIs'],
          icon: 'assets/icon-kds-map.webp',
          screenshot: 'assets/screenshot-kds-map.webp',
          summary: 'Domain-specific interactive map for visualizing and selecting geolocated audit cases across the whole portfolio.',
          contributions: [
            { t: 'Filtering UX', d: 'By stage, type and organization' },
            { t: 'Satellite view', d: 'Clustered buildings across the portfolio' },
            { t: 'Business data', d: 'Real-time integration' },
          ],
        },
        {
          id: 'mousquetaires',
          video: 'assets/mousquetaires-demo.mp4',
          name: 'Pallet-truck app · Intermarché',
          context: 'SAÉ · IUT Valence × Les Mousquetaires · 2025-2026',
          stack: ['React', 'Symfony', 'REST API'],
          logo: 'assets/logo-mousquetaires.webp',
          screenshot: 'assets/screenshot-mousquetaires-dashboard.webp',
          gallery: [
            'assets/screenshot-mousquetaires-login.webp',
            'assets/screenshot-mousquetaires-dashboard.webp',
            'assets/screenshot-mousquetaires-dashboard-2.webp',
            'assets/screenshot-mousquetaires-gestion.webp',
            'assets/screenshot-mousquetaires-supports.webp',
            'assets/screenshot-mousquetaires-preparation.webp',
          ],
          summary: 'Mobile app embedded on a pallet truck for order pickers in a refrigerated warehouse, designed to guide them and streamline their picking routes.',
          contributions: [
            { t: 'Field requirements', d: 'Gathered on site, in a refrigerated warehouse' },
            { t: 'React front-end', d: 'Tuned for gloves + touch usage' },
            { t: 'Symfony API', d: 'Manages the picking routes' },
          ],
        },
        {
          id: 'crm-airtable',
          name: 'Internal Airtable CRM',
          context: 'KDS · 2025',
          stack: ['Airtable', 'Automations', 'Integrations'],
          logo: 'assets/airtable-logo.webp',
          summary: 'End-to-end Airtable CRM: modeling, automations and integration with internal flows.',
          contributions: [
            { t: 'Audit', d: 'Review of existing processes' },
            { t: 'Modeling', d: 'Relational CRM entities' },
            { t: 'Automations', d: 'Views and flows filtered by team' },
          ],
        },
        {
          id: 'chandezon',
          video: 'assets/chandezon-demo.mp4',
          name: 'Dr Chandezon website',
          context: 'Internship · 2024 — 2025',
          stack: ['PHP', 'MySQL', 'HTML/CSS', 'Figma'],
          logo: 'assets/icon-chandezon.webp',
          screenshot: 'assets/screenshot-chandezon.webp',
          gallery: [
            'assets/screenshot-chandezon.webp',
            'assets/screenshot-chandezon-about.webp',
            'assets/screenshot-chandezon-care.webp',
          ],
          summary: 'Showcase site and patient portal for a morphological & anti-aging medical practice — from Figma mockups to deployment.',
          contributions: [
            { t: 'Figma mockups', d: 'Interactive prototypes approved with the client' },
            { t: 'Full-Stack', d: 'PHP/MySQL development and relational database' },
            { t: 'Go-live', d: 'Deployed at drchandezon.fr' },
          ],
          link: 'https://drchandezon.fr',
        },
      ],
    },
    skills: {
      title: 'Technical skills',
      groups: [
        { label: 'Web Development', items: ['HTML/CSS', 'JavaScript', 'TypeScript', 'PHP', 'React', 'Symfony'] },
        { label: 'Software Development', items: ['Java', 'Python', 'C', 'C++', 'C#', 'Rust'] },
        { label: 'Mobile', items: ['Flutter', 'React Native', 'React Expo', 'Kotlin'] },
        { label: 'Databases', items: ['SQL', 'Neo4j', 'Firestore', 'Power BI'] },
        { label: 'Tools & Methods', items: ['Docker', 'GitLab CI/CD', 'ESXi', 'Godot', 'Modélio'] },
      ],
    },
    education: {
      title: 'Education',
      items: [
        { period: '2023 — 2026', degree: 'BUT in CS · Application Development', school: 'IUT de Valence — UGA · 3rd year as an apprenticeship', logo: 'assets/logo-iut-valence.webp' },
        { period: '2022 — 2023', degree: 'French Baccalauréat · Honors', school: 'Lycée les Catalins, Montélimar' },
      ],
    },
    interests: {
      title: 'Interests',
      music: {
        label: 'Music',
        lead: 'A big chunk of my downtime lives inside headphones. Three families above all:',
        genres: [
          { name: 'Jazz Rap', note: 'Brass samples, laid-back flows, lyrical craft' },
          { name: 'Soul', note: 'Voice, groove, 60s–70s classics' },
          { name: 'R&B', note: 'Modern production, late-night moods' },
        ],
      },
      items: [
        { k: 'Football', v: 'Casual play and following competitions' },
        { k: 'Journalism & geopolitics', v: 'International current affairs' },
        { k: 'Audiovisual culture', v: 'Cinema, series, documentaries' },
      ],
    },
    contact: {
      title: 'Contact',
      lead: 'I\u2019m available to discuss a role, a project or an engineering school application.',
      email: 'roman.theo.rodriguez@gmail.com',
      phone: '+33 7 50 02 64 78',
      city: 'Valence, France',
      languages: 'French · English B2 · Spanish A2',
      cv: 'Download résumé (PDF)',
      linkedin: 'https://www.linkedin.com/in/roman-rodriguez-b34a96376/',
      github: 'https://github.com/Vaxen69',
    },
    misc: { available: 'Available · apprenticeship & engineering school', viewProject: 'View project', backToList: 'Back' },
  },
};
